@startuml API. Диаграмма компонентов
title "C4. Компоненты сервиса обмена валют"

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons"
!include $ICONURL/common.puml
!include $ICONURL/devicons/react.puml
!include $ICONURL/devicons/java.puml

Component(currencyExchangeService, "Сервис обмена валют", "Java", $sprite="java")

System_Boundary(currencyExchangeBoundary, "Currency Exchange Service") {

    Component(CurrencyExchangeAPI, "CurrencyExchangeControler", "Java", "API для обработки запросов на обмен валюты")
    Component(CurrencyExchangeProcessor, "CurrencyExchangeService", "Java", "Основная логика обработки обмена валюты")
    Component(RateRepository, "RateRepository", "Java", "Получение актуальных курсов валют из БД")
    Component(UserAccountsRepository, "UserAccountsRepository", "Java", "Получение информации о пользователях")
}

Component(ExchangeRatesDB, "DB", "PostgreSQL", "Хранение актуальных данных")

Component(webApp, "Веб-приложение", "React", "Интерфейс для пользователей для обмена валют и проверки курсов")

webApp --> CurrencyExchangeAPI : "Запросы на обмен валюты"
CurrencyExchangeAPI --> CurrencyExchangeProcessor : "Обработка запросов на обмен валюты"
CurrencyExchangeProcessor --> RateRepository : "Запрос актуальных курсов валют"
CurrencyExchangeProcessor --> UserAccountsRepository : "Проверка баланса"
RateRepository --> ExchangeRatesDB : "Запрос курсов валют"
UserAccountsRepository --> ExchangeRatesDB : "Запрос информации о пользователях"

Component(EventBus, "EventBus", "RabbitMQ", "Обработка и маршрутизация событий")

CurrencyExchangeProcessor ---> EventBus : "Публикация события обмена валюты"

@enduml