@startuml Система обмена валют. Обслуживание

'left to right direction	
top to bottom direction

package "Разработка" {
    [Разработчик]
    [Система контроля версий]
    [Разработчик] --> [Система контроля версий]: "коммит" 

    [CI]
    [Система контроля версий] --> [CI]: "тестирование и сборка"

    [CD]
    [CI] --> [CD]
    [CI] --> [Система контроля версий]: "слияние в мастер"
}

package "Docker compose" {  
    [Docker]
    [Контейнеры] 
}
[Docker] --> [Система контроля версий]: "получить основную версию"
[Docker] --> [Контейнеры]: "сборка и развертывание" 
[CD] --> [Docker]: "развернуть" 

package "Мониторинг и резервное копирование" {
    [Zabbix]
    [Zabbix] --> [Контейнеры]: "проверка состояния" 
    [Zabbix] --> [Сервис резервного копирования]: "отправка уведомлений" 
    [Сервис резервного копирования]
    [Сервис резервного копирования] --> [Контейнеры]: "создание резервных копий" 
}

@enduml